backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "src/pages/index.md"
        label: "Index pagina"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
      - file: "src/pages/home/index.md"
        label: "Home pagina"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Intro, name: intro, widget: object, fields: [{label: Titel, name: title, widget: string},{label: Hoofd afbeelding, name: mainImage, widget: image},{label: Hoofd tekst, name: mainText, widget: text},{label: Call to action, name: cta, widget: string}]}
          - {label: Diensten Block, name: servicesBlock, widget: object, fields: [{label: Titel, name: title, widget: string}, {label: Introtekst, name: introText, widget: text}, {label: Diensten, name: services, widget: list, fields: [{label: Titel, name: title, widget: string}, {label: Broodtekst, name: breadtext, widget: string}]}]}
          - {label: Over Evisie, name: about, widget: object, fields: [{label: Titel, name: title, widget: string},{label: Afbeelding, name: aboutImage, widget: image},{label: Over Evisie tekst, name: mainText, widget: markdown}]}
          - {label: Review block, name: reviews, widget: object, fields: [{label: Titel, name: title, widget: string},{label: Reviews, name: reviews, widget: list, fields: [{label: Titel, name: title, widget: string}, {label: Logo, name: logo, widget: image},{label: Review, name: review, widget: text},{label: Naam, name: name, widget: string},{label: Functie, name: job, widget: string}]}]}
          - {label: Contact, name: contact, widget: object, fields: [{label: Titel, name: title, widget: string},{label: Tekst, name: introText, widget: text}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - { label: 'Subtitel', name: 'subtitle', widget: 'string', required: false }
          - {label: "Intro", name: "introText", widget: "markdown"}
          - label: 'Pagina'
            name: 'page'
            widget: 'list'
            types:
              - label: 'Tekst blok'
                name: 'text_block'
                widget: 'object'
                required: false
                fields:
                  - { label: 'Titel', name: 'title', widget: 'string', required: false }
                  - {label: Kolommen, name: columns, widget: list, fields: [{label: Tekst, name: text, widget: markdown}]}
              - label: 'Foto blok'
                name: 'foto_block'
                widget: 'object'
                required: false
                fields:
                  - { label: 'Titel', name: 'title', widget: 'string', required: false }
                  - {label: Kolommen, name: fotos, widget: list, fields: [{label: Foto, name: foto, widget: image}]}
      - file: "src/pages/diensten/index.md"
        label: "Diensten"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Title", name: "title", widget: "string"}
          - { label: 'Subtitel', name: 'subtitle', widget: 'string', required: false }
          - {label: "Intro", name: "introText", widget: "markdown"}
          - label: 'Pagina'
            name: 'page'
            widget: 'list'
            types:
              - label: 'Tekst blok'
                name: 'text_block'
                widget: 'object'
                required: false
                fields:
                  - { label: 'Titel', name: 'title', widget: 'string', required: false }
                  - {label: Kolommen, name: columns, widget: list, fields: [{label: Tekst, name: text, widget: markdown}]}
              - label: 'Foto blok'
                name: 'foto_block'
                widget: 'object'
                required: false
                fields:
                  - { label: 'Titel', name: 'title', widget: 'string', required: false }
                  - {label: Kolommen, name: fotos, widget: list, fields: [{label: Foto, name: foto, widget: image}]}